export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  EXPENSE: "/expense",
  ADD_EXPENSE: "/expense/add",
  EXPENSE_BY_DATE: "/expense/:date",
  EXPENSE_BY_ID: "/expense/:date/:id",
  REVENUE: "/revenue",
  ADD_REVENUE: "/revenue/add",
  REVENUE_BY_DATE: "/revenue/:date",
  REVENUE_BY_ID: "/revenue/:date/:id",
  INVESTMENT: "/investment",
  ADD_INVESTMENT: "/investment/add",
  INVESTMENT_BY_STATUS: "/investment/:status",
  INVESTMENT_BY_ID: "/investment/:status/:id",
  STATISTICS: "/statistics",
  PROFILE: "/profile",
  MARK: "/mark",
  LOGIN: "/login",
  SIGNUP: "/signup",
  SESSION_TIMED_OUT: "/session-timed-out",
};
