export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  EXPENSE: "/expense",
  ADD_EXPENSE: "/expense/add",
  EXPENSE_BY_DATE: "/expense/:date",
  REVENUE: "/revenue",
  ADD_REVENUE: "/revenue/add",
  REVENUE_BY_DATE: "/revenue/:date",
  INVESTMENT: "/investment",
  ADD_INVESTMENT: "/investment/add",
  ADD_TRANSACTION_INVESTMENT: "/investment/:id/add",
  INVESTMENT_BY_ID: "/investment/:id",
  INVESTMENT_ORDER: "/investment/order",
  STATISTICS: "/statistics",
  PROFILE: "/profile",
  LOGIN: "/login",
  SIGNUP: "/signup",
  SESSION_TIMED_OUT: "/session-timed-out",
};
