# docker-compose.yml

services:
  frontend:
    image: ghcr.io/hugolgle/fintrack-frontend:latest
    container_name: fintrack-frontend
    networks:
      - mongo_network
      - caddy_net
    restart: unless-stopped

  backend:
    container_name: fintrack-backend
    image: ghcr.io/hugolgle/fintrack-backend:latest
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/mydatabase?authSource=admin
      - JWT_SECRET=bR9!zT@4wV#qLm2^sP$eX1%jUo8&kNzA
      - CLIENT_URL=https://fintrack.hugolge.fr
      - NODE_ENV=production
    networks:
      - mongo_network
      - caddy_net
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    networks:
      - mongo_network
    restart: unless-stopped

networks:
  mongo_network:
    driver: bridge
  caddy_net:
    external: true

volumes:
  mongo-data:
