# .guthub/workflows/deploy.yml
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Generate .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ./frontend/.env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> ./frontend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./frontend/.env

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/hugolgle/fintrack-frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/hugolgle/fintrack-backend:latest

      - name: Copy docker compose
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/fintrack"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u hugolgle --password-stdin
            docker pull ghcr.io/hugolgle/fintrack-frontend:latest
            docker pull ghcr.io/hugolgle/fintrack-backend:latest
            cd /home/ubuntu/fintrack
            docker compose down
            docker compose up -d
